# Bag Of Words

In [1]:
txt_data=['I am interested in nlp','I went through this by practising','I implement this through python','Feature extraction is important']

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
bow=CountVectorizer(stop_words='english')

In [3]:
#fit the data
bow.fit(txt_data)

CountVectorizer(stop_words='english')

In [4]:
#get the vocabulary list
bow.get_feature_names()

C:\Users\showm\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['extraction',
 'feature',
 'implement',
 'important',
 'interested',
 'nlp',
 'practising',
 'python',
 'went']

In [5]:
bow_features=bow.transform(txt_data)
bow_features

<4x9 sparse matrix of type '<class 'numpy.int64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [6]:
bow_feature_array=bow_features.toarray()
bow_feature_array

array([[0, 0, 0, 0, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 1],
       [0, 0, 1, 0, 0, 0, 0, 1, 0],
       [1, 1, 0, 1, 0, 0, 0, 0, 0]], dtype=int64)

In [8]:
print(bow.get_feature_names())
for sentence,feature in zip(txt_data,bow_feature_array):
    print(sentence)
    print(feature)

['extraction', 'feature', 'implement', 'important', 'interested', 'nlp', 'practising', 'python', 'went']
I am interested in nlp
[0 0 0 0 1 1 0 0 0]
I went through this by practising
[0 0 0 0 0 0 1 0 1]
I implement this through python
[0 0 1 0 0 0 0 1 0]
Feature extraction is important
[1 1 0 1 0 0 0 0 0]


C:\Users\showm\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
